service: awslambdaserviceafp

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role: arn:aws:iam::924779871934:role/LabRole

functions:
  # funzione di Default
  hello:
    handler: handler.hello

  getTicket:
    handler: get.getTicket
  insertTicket:
    handler: insert.insertTicket
  deleteTicket:
    handler: delete.deleteTicket
  updateTicket:
    handler: update.updateTicket