service: awsafp-lessons-3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role: arn:aws:iam::924779871934:role/LabRole

functions:
  getTicket:
    handler: get.getTicket
    events:
      - http:
          path: /api/get-ticket
          method: get
          cors: true

  insertTicket:
    handler: insert.insertTicket
    events:
      - http:
          path: /api/insert-ticket
          method: post
          cors: true

  deleteTicket:
    handler: delete.deleteTicket
    events:
      - http:
          path: /api/delete-ticket/{id}
          method: delete
          cors: true
          
  updateTicket:
    handler: update.updateTicket
    events:
      - http:
          path: /api/update-ticket
          method: put
          cors: true
